### PR TITLE
refactor:first input title then save

### PR DESCRIPTION
**Pull request by imgss**
when user choose to save，someone like me, he may not notice the title input box，and just check the svg file.

### CODE REVIEW

**Comment by antfu** [comment]
Hi. How about let's make it using system prompt? 

Something like this:
image

**Comment by antfu** [comment]
Oh sorry, I misunderstand your point. I think your approach is more reasonable. Thanks!

**Comment by antfu** [comment]
@imgss It's released in v0.8.4. Thanks!

**Comment by imgss** [comment]
Thanks! 🍻

**Pull request merged**
